global:
  scrape_interval: 1s # How often Prometheus scrapes targets
  evaluation_interval: 1s # How often Prometheus evaluates rules

scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['0.0.0.0:9100'] # Assumes Node Exporter is running on the local >
      
  - job_name: 'pushgateway'
    static_configs:
      - targets: ['0.0.0.0:9091'] # Assumes Node Exporter is running on the local >
